### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by RachelDuffin**
First implementation of the samplesheet_validator

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3)

### CODE REVIEW

**Review by rebeccahaines1 — CHANGES_REQUESTED** [review]
> Reviewed 41 of 49 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3)* status: all files reviewed, 7 unresolved discussions (waiting on @RachelDuffin)

___
*[`pytest.ini` line 2 at r2](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3#-NlO10f58TmpbzgrfBgs:-NlO10f58TmpbzgrfBgt:bn3b9gw) ([raw file](https://github.com/moka-guys/samplesheet_validator/blob/27a64c0c92a66a63448f3bfbadd081f053569759/pytest.ini#L2)):*
> ```INI
> [pytest]
> addopts = -v --ignore=test/data/ --ignore=test/temp/ --cov=. --cov-report term-missing --sequencer_ids=NB551068,NB552085,M02353,M02631,A01229 --library_prep_names=ADX,NGS,TSO,SNP,DEV --tso_panels=Pan4969,Pan5085,Pan5112,Pan5114 --dev_panno=Pan5180 --panels=Pan5180,Pan4009,Pan2835,Pan4940,Pan4396,Pan5113,Pan5115,Pan4969,Pan5085,Pan5112,Pan5114,Pan5007,Pan5008,Pan5009,Pan5010,Pan5011,Pan5012,Pan5013,Pan5014,Pan5015,Pan5016,Pan4119,Pan4121,Pan4122,Pan4125,Pan4126,Pan4974,Pan4975,Pan4976,Pan4977,Pan4978,Pan4979,Pan4980,Pan4981,Pan4982,Pan4983,Pan4984,Pan4821,Pan4822,Pan4823,Pan4824,Pan4825,Pan4149,Pan4150,Pan4129,Pan4964,Pan4130,Pan5121,Pan5185,Pan5186,Pan5143,Pan5147,Pan4816,Pan4817,Pan5122,Pan5144,Pan5148,Pan4819,Pan4820,Pan4145,Pan4146,Pan4132,Pan4134,Pan4136,Pan4137,Pan4138,Pan4143,Pan4144,Pan4151,Pan4314,Pan4351,Pan4387,Pan4390,Pan4826,Pan4827,Pan4828,Pan4829,Pan4830,Pan4831,Pan4832,Pan4833,Pan4834,Pan4835,Pan4836 --logdir=/home/rachel/projects/samplesheet_validator/
> ```

--logdir is a location on your computer. I know this is for the test suite so not a particular concern here, but it's not ideal. is there an easy fix for this?
___
*[`samplesheet_validator/samplesheet_validator.py` line 115 at r3](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3#-NmkXpIA88qL0MrHvFwg:-NmkXpIA88qL0MrHvFwh:bfthbkh) ([raw file](https://github.com/moka-guys/samplesheet_validator/blob/5a8783ec87b76ae00b5776a072b42ede625a3bf3/samplesheet_validator/samplesheet_validator.py#L115)):*
> ```Python
>         # Store sample IDs and sample names from samplesheet
>         self.samples = {"Sample_ID": [], "Sample_Name": []}
>         self.errors = False  # Switches to True if samplesheet errors encountered
> ```

I find these types of comments very helpful, thank you
___
*[`samplesheet_validator/samplesheet_validator.py` line 229 at r3](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3#-NmlOrJ44vxwexLSXP4u:-NmlOrJ44vxwexLSXP4v:byysvt0) ([raw file](https://github.com/moka-guys/samplesheet_validator/blob/5a8783ec87b76ae00b5776a072b42ede625a3bf3/samplesheet_validator/samplesheet_validator.py#L229)):*
> ```Python
>             :param sscheck_obj (object):    Object created by
>                                             samplesheet_validator.SampleheetCheck
>             :return True | None:            True if contains dev pan numbers, false if does not
> ```

why is it returning None instead of False?
edit: I can see that other functions return true or none, so this is consistent. Can you just clarify in the doc string here what is being returned? Thanks
___
*[`test/conftest.py` line 40 at r3](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3#-NmkQ1tp7aITOup5SvUR:-NmkQ1tp7aITOup5SvUS:b-yn8c1x) ([raw file](https://github.com/moka-guys/samplesheet_validator/blob/5a8783ec87b76ae00b5776a072b42ede625a3bf3/test/conftest.py#L40)):*
> ```Python
>         required=True,
>     )
>     parser.addoption("--dev_panno", action="store", type=str, required=True)
> ```

I know this is incredibly picky and I probably wouldn't bother if there weren't a couple of other things, but can the formatting here be consistent with the rest of the function please?
___
*[`test/test_samplesheet_validator.py` line 333 at r3](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3#-NmlT4r38Nfkt3lKtcCN:-NmlT4r38Nfkt3lKtcCO:bj4kr3c) ([raw file](https://github.com/moka-guys/samplesheet_validator/blob/5a8783ec87b76ae00b5776a072b42ede625a3bf3/test/test_samplesheet_validator.py#L333)):*
> ```Python
>             os.getenv("samplesheet_dir"),
>             "invalid",
>             "211008_A01229_AHKGTFDRXY_samplesheet.abc",
> ```

is it right to be using this as a test for the invalid extension, when it's also got an incorrect naming format (missing the auto incrementing number)? I'm mostly just curious about this
___
*[`test/data/samplesheets/invalid/2110915_M02353_0632_000000000-K242J_SampleSheet.csv` line 22 at r3](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3#-Nmk_xO6Ba-xWVCe0oSQ:-Nmk_xO6Ba-xWVCe0oSR:b-wg0g3v) ([raw file](https://github.com/moka-guys/samplesheet_validator/blob/5a8783ec87b76ae00b5776a072b42ede625a3bf3/test/data/samplesheets/invalid/2110915_M02353_0632_000000000-K242J_SampleSheet.csv#L22)):*
> ```CSV
> [Data],,,,,,,,,
> Sample_ID,Sample_Name,Sample_Plate,Sample_Well,I7_Index_ID,index,I5_Index_ID,index2,Sample_Project,Description
> SNP003_01_240602_4014274593_MH_F_SNPIDv2_Pan4009,SNP003_01_240602_4014274593_MH_F_SNPIDv2_Pan4009,RCPCR96,A08,7057,ATGCCTCTTC,5057,GATAAGGCAA,,
> ```

these are NHS numbers. Need to remove/anonymise these
___
*[`test/data/samplesheets/valid/231116_NB551068_0551_AHLCYNAFX5_SampleSheet.csv` line 20 at r3](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3#-NmkT2hB6WCPzWpknY8A:-NmkT2hB6WCPzWpknY8B:b-cssi0z) ([raw file](https://github.com/moka-guys/samplesheet_validator/blob/5a8783ec87b76ae00b5776a072b42ede625a3bf3/test/data/samplesheets/valid/231116_NB551068_0551_AHLCYNAFX5_SampleSheet.csv#L20)):*
> ```CSV
> [Data],,,,,,,,,
> Sample_ID,Sample_Name,Sample_Plate,Sample_Well,I7_Index_ID,index,I5_Index_ID,index2,Sample_Project,Description
> SNP126_01_155533_4048339841_AO_F_SNPIDv2_Pan4009_RP1,SNP126_01_155533_4048339841_AO_F_SNPIDv2_Pan4009_RP1,RCPCR96,A01,7001,CATGCGAGAA,5001,TGAGCCGCGG,,
> ```

more NHS numbers

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3)* status: all files reviewed, 7 unresolved discussions (waiting on @rebeccahaines1)

___
*[`pytest.ini` line 2 at r2](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3#-NlO10f58TmpbzgrfBgs:-NnAQi832wVqFtBi4kIr:bb6un1j) ([raw file](https://github.com/moka-guys/samplesheet_validator/blob/27a64c0c92a66a63448f3bfbadd081f053569759/pytest.ini#L2)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

--logdir is a location on your computer. I know this is for the test suite so not a particular concern here, but it's not ideal. is there an easy fix for this?
</blockquote></details>

Done
___
*[`samplesheet_validator/samplesheet_validator.py` line 115 at r3](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3#-NmkXpIA88qL0MrHvFwg:-NnAQnfQ5bOQHyuUCyFi:bb6vman) ([raw file](https://github.com/moka-guys/samplesheet_validator/blob/5a8783ec87b76ae00b5776a072b42ede625a3bf3/samplesheet_validator/samplesheet_validator.py#L115)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

I find these types of comments very helpful, thank you
</blockquote></details>

Fab!
___
*[`samplesheet_validator/samplesheet_validator.py` line 229 at r3](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3#-NmlOrJ44vxwexLSXP4u:-NnATYCn4UQ8sPiqv1W6:b-49jjji) ([raw file](https://github.com/moka-guys/samplesheet_validator/blob/5a8783ec87b76ae00b5776a072b42ede625a3bf3/samplesheet_validator/samplesheet_validator.py#L229)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

why is it returning None instead of False?
edit: I can see that other functions return true or none, so this is consistent. Can you just clarify in the doc string here what is being returned? Thanks
</blockquote></details>

Ah yes my comment is wrong - have updated it. Thanks!
___
*[`test/conftest.py` line 40 at r3](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3#-NmkQ1tp7aITOup5SvUR:-NnATo6g8DFlIPDBo2zb:bb6un1j) ([raw file](https://github.com/moka-guys/samplesheet_validator/blob/5a8783ec87b76ae00b5776a072b42ede625a3bf3/test/conftest.py#L40)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

I know this is incredibly picky and I probably wouldn't bother if there weren't a couple of other things, but can the formatting here be consistent with the rest of the function please?
</blockquote></details>

Done
___
*[`test/test_samplesheet_validator.py` line 333 at r3](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3#-NmlT4r38Nfkt3lKtcCN:-NnAVl9W5eUFbV2haMkh:b-9ia70h) ([raw file](https://github.com/moka-guys/samplesheet_validator/blob/5a8783ec87b76ae00b5776a072b42ede625a3bf3/test/test_samplesheet_validator.py#L333)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

is it right to be using this as a test for the invalid extension, when it's also got an incorrect naming format (missing the auto incrementing number)? I'm mostly just curious about this
</blockquote></details>

Great spot youre right, have amended this now!

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3)* status: 20 of 50 files reviewed, 7 unresolved discussions (waiting on @rebeccahaines1)

___
*[`test/data/samplesheets/invalid/2110915_M02353_0632_000000000-K242J_SampleSheet.csv` line 22 at r3](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3#-Nmk_xO6Ba-xWVCe0oSQ:-NnAg5nw4fd_plExmHdC:bb6un1j) ([raw file](https://github.com/moka-guys/samplesheet_validator/blob/5a8783ec87b76ae00b5776a072b42ede625a3bf3/test/data/samplesheets/invalid/2110915_M02353_0632_000000000-K242J_SampleSheet.csv#L22)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

these are NHS numbers. Need to remove/anonymise these
</blockquote></details>

Done
___
*[`test/data/samplesheets/valid/231116_NB551068_0551_AHLCYNAFX5_SampleSheet.csv` line 20 at r3](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3#-NmkT2hB6WCPzWpknY8A:-NnAg8yZ3V468E2C_XAL:bb6un1j) ([raw file](https://github.com/moka-guys/samplesheet_validator/blob/5a8783ec87b76ae00b5776a072b42ede625a3bf3/test/data/samplesheets/valid/231116_NB551068_0551_AHLCYNAFX5_SampleSheet.csv#L20)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

more NHS numbers
</blockquote></details>

Done

**Review by rebeccahaines1 — COMMENTED** [review]
> Reviewed 30 of 30 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3)* status: all files reviewed, 1 unresolved discussion (waiting on @RachelDuffin)

**Review by rebeccahaines1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/samplesheet_validator/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RachelDuffin)

**Pull request merged**
